const fs = require("fs");
const path = require("path");

/**
 * Generate an HTML report from a comparison result and write it to disk.
 *
 * @param {object} report - Comparison report from comparePixels()
 * @param {string} outputPath - File path for the HTML output
 * @param {object[]} [scanResults] - Raw scan results from interceptor (for debug section)
 */
function generateReport(report, outputPath, scanResults) {
  const html = buildHtml(report, scanResults);
  fs.writeFileSync(outputPath, html, "utf-8");
  console.log(`\nReport saved to: ${path.resolve(outputPath)}`);
}

function buildHtml(report, scanResults) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pixel Comparator Report</title>
<style>
${getStyles()}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>Pixel Comparator Report</h1>
    <p class="subtitle">TikTok vs Meta/Facebook Pixel Comparison</p>
    <p class="meta">Generated: ${new Date(report.generatedAt).toLocaleString()}</p>
  </header>

  ${renderSummary(report.summary)}

  ${report.pages.map((page, i) => renderPage(page, i)).join("\n")}

  ${scanResults ? renderDebugSection(scanResults) : ""}

  <footer>
    <p>Generated by <strong>pixel-comparator</strong></p>
  </footer>
</div>
</body>
</html>`;
}

function renderSummary(summary) {
  return `
  <section class="summary-section">
    <h2>Overall Summary</h2>
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-value">${summary.pagesScanned}</div>
        <div class="stat-label">Pages Scanned</div>
      </div>
      <div class="stat-card tiktok">
        <div class="stat-value">${summary.totalTikTokEvents}</div>
        <div class="stat-label">TikTok Events</div>
        <div class="stat-detail">${summary.tiktokPixelIds.length} pixel ID(s)</div>
      </div>
      <div class="stat-card meta">
        <div class="stat-value">${summary.totalMetaEvents}</div>
        <div class="stat-label">Meta Events</div>
        <div class="stat-detail">${summary.metaPixelIds.length} pixel ID(s)</div>
      </div>
    </div>

    ${summary.tiktokPixelIds.length > 0 ? `
    <div class="pixel-ids">
      <strong>TikTok Pixel IDs:</strong> ${summary.tiktokPixelIds.map((id) => `<code>${esc(id)}</code>`).join(", ")}
    </div>` : ""}

    ${summary.metaPixelIds.length > 0 ? `
    <div class="pixel-ids">
      <strong>Meta Pixel IDs:</strong> ${summary.metaPixelIds.map((id) => `<code>${esc(id)}</code>`).join(", ")}
    </div>` : ""}

    ${renderObservations(summary.overallObservations)}
  </section>`;
}

function renderPage(page, index) {
  // Render per-TikTok-pixel comparison sections (each contains per-Meta-pixel sub-comparisons)
  const pixelSections = page.pixelComparisons.map((pc) =>
    renderPixelComparison(pc)
  ).join("\n");

  // Render Meta-only events (not matched by any TikTok pixel)
  const metaOnlySection = page.metaOnlyEvents && page.metaOnlyEvents.length > 0
    ? renderMetaOnlySection(page.metaOnlyEvents, page.meta)
    : "";

  const redirectNote = page.redirectChain
    ? renderRedirectChain(page.redirectChain)
    : page.originalUrl
      ? `<div class="redirect-notice">Redirected from <a href="${esc(page.originalUrl)}" target="_blank">${esc(page.originalUrl)}</a></div>`
      : "";

  return `
  <section class="page-section">
    <h2>Page ${index + 1}: <a href="${esc(page.url)}" target="_blank">${esc(page.url)}</a></h2>
    ${redirectNote}

    <div class="stats-grid">
      <div class="stat-card tiktok small">
        <div class="stat-value">${page.tiktok.eventCount}</div>
        <div class="stat-label">TikTok Events</div>
        <div class="stat-detail">${page.tiktok.pixelIds.length} pixel ID(s)</div>
      </div>
      <div class="stat-card meta small">
        <div class="stat-value">${page.meta.eventCount}</div>
        <div class="stat-label">Meta Events</div>
        <div class="stat-detail">${page.meta.pixelIds.length} pixel ID(s)</div>
      </div>
    </div>

    ${pixelSections}
    ${metaOnlySection}
    ${renderObservations(page.observations)}
  </section>`;
}

/**
 * Render a redirect chain as a visual hop-by-hop list.
 */
function renderRedirectChain(chain) {
  if (!chain || chain.length < 2) return "";
  const hops = chain.length - 1;
  const steps = chain.map((url, i) => {
    const label = i === 0 ? "Original" : i === chain.length - 1 ? "Final" : `Hop ${i}`;
    return `<div class="redirect-step"><span class="redirect-label">${label}</span> <a href="${esc(url)}" target="_blank">${esc(url)}</a></div>`;
  }).join('<div class="redirect-arrow">&darr;</div>');

  return `
    <div class="redirect-notice">
      <strong>Redirect chain (${hops} hop${hops > 1 ? "s" : ""}):</strong>
      <div class="redirect-chain">${steps}</div>
    </div>`;
}

/**
 * Render a comparison section for a single TikTok pixel, containing
 * sub-sections for each Meta pixel sorted by health score (highest first).
 */
function renderPixelComparison(pc) {
  const metaSections = pc.metaComparisons.map((mc) =>
    renderMetaSubComparison(mc)
  ).join("\n");

  const comparisonCount = pc.metaComparisons.length;
  const subtitle = comparisonCount > 0
    ? `${pc.tiktokEventCount} TikTok event(s) compared against ${comparisonCount} Meta pixel(s) — sorted by match score`
    : `${pc.tiktokEventCount} TikTok event(s) — no Meta pixels to compare against`;

  return `
    <div class="pixel-comparison-section">
      <h3>TikTok Pixel <code>${esc(pc.tiktokPixelId)}</code></h3>
      <p class="pixel-comparison-meta">${subtitle}</p>
      ${comparisonCount === 0 ? '<p class="no-data">No Meta pixels detected on this page.</p>' : ""}
      ${metaSections}
    </div>`;
}

/**
 * Render a sub-comparison for a single Meta pixel within a TikTok pixel group.
 */
function renderMetaSubComparison(mc) {
  return `
      <div class="meta-comparison-subsection">
        <h4>vs Meta Pixel <code>${esc(mc.metaPixelId)}</code>
          <span class="meta-event-count">${mc.metaEventCount} event(s)</span>
        </h4>
        ${renderHealthSummary(mc.health)}
        ${renderEventComparisonTable(mc.eventComparison, mc.paramComparison)}
      </div>`;
}

/**
 * Render a section for Meta-only events that weren't matched by any TikTok pixel.
 */
function renderMetaOnlySection(metaOnlyEvents, meta) {
  const rows = metaOnlyEvents
    .map((e) => {
      const params = e.customData && Object.keys(e.customData).length > 0
        ? e.customData
        : {};
      return `
      <tr class="meta_only">
        <td><strong>${esc(e.eventName)}</strong></td>
        <td>${esc(e.pixelId || "—")}</td>
        <td><span class="badge ${e.eventCategory}">${esc(e.eventCategory)}</span></td>
        <td><code class="params">${esc(JSON.stringify(params, null, 0))}</code></td>
      </tr>`;
    })
    .join("\n");

  return `
    <div class="pixel-comparison-section">
      <h3>Meta-Only Events</h3>
      <p class="pixel-comparison-meta">Events firing on Meta but not matched by any TikTok pixel.</p>
      <div class="table-wrapper">
      <table class="detail-table">
        <thead><tr><th>Event</th><th>Pixel ID</th><th>Category</th><th>Parameters</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      </div>
    </div>`;
}

function renderHealthSummary(health) {
  if (!health) return "";

  const issueItems = health.issues
    .map((issue) => `<li>${esc(issue)}</li>`)
    .join("\n");

  return `
    <div class="health-card ${health.rating}">
      <div class="health-score-ring">
        <svg viewBox="0 0 36 36" class="health-circle">
          <path class="health-circle-bg" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"/>
          <path class="health-circle-fg" stroke-dasharray="${health.score}, 100" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"/>
          <text x="18" y="20.5" class="health-score-text">${health.score}</text>
        </svg>
      </div>
      <div class="health-body">
        <div class="health-label"><span class="badge health-${health.rating}">${esc(health.label)}</span> Pixel Alignment</div>
        <p class="health-explanation">${esc(health.explanation)}</p>
        ${health.issues.length > 0 ? `<ul class="health-issues">${issueItems}</ul>` : ""}
      </div>
    </div>`;
}

function renderEventComparisonTable(comparison, paramComparisons) {
  if (comparison.mapped.length === 0) {
    return `<p class="no-data">No events to compare.</p>`;
  }

  // Index param comparisons by event name for fast lookup
  const paramsByEvent = {};
  for (const pc of paramComparisons) {
    paramsByEvent[pc.eventName] = pc;
    if (pc.metaEquivalent && pc.metaEquivalent !== pc.eventName) {
      paramsByEvent[pc.metaEquivalent] = pc;
    }
  }

  const rows = comparison.mapped
    .map((m) => {
      const statusClass = m.status;
      const statusLabel = {
        matched: "Matched",
        count_mismatch: "Count Mismatch",
        tiktok_only: "TikTok Only",
        meta_only: "Meta Only",
      }[m.status];

      // Build the event row
      let html = `
      <tr class="event-row ${statusClass}">
        <td>${esc(m.tiktokEvent || "—")}</td>
        <td>${m.tiktokCount}</td>
        <td>${esc(m.metaEvent || "—")}</td>
        <td>${m.metaCount}</td>
        <td><span class="badge ${statusClass}">${statusLabel}</span></td>
        <td>${esc(m.note)}</td>
      </tr>`;

      // Find param comparison for this event
      const pc = paramsByEvent[m.tiktokEvent] || paramsByEvent[m.metaEvent];
      if (pc) {
        const paramHtml = renderInlineParams(pc);
        if (paramHtml) {
          html += `
      <tr class="param-subrow">
        <td colspan="6">${paramHtml}</td>
      </tr>`;
        }
      }

      return html;
    })
    .join("\n");

  return `
    <h3>Event &amp; Parameter Comparison</h3>
    <div class="table-wrapper">
    <table class="comparison-table">
      <thead>
        <tr>
          <th>TikTok Event</th>
          <th>Count</th>
          <th>Meta Event</th>
          <th>Count</th>
          <th>Status</th>
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
      </tbody>
    </table>
    </div>`;
}

/**
 * Render parameter comparison as an expandable details block for inline use
 * inside the event comparison table.
 */
function renderInlineParams(pc) {
  const totalParams = pc.matches.length + pc.differences.length + pc.tiktokOnly.length + pc.metaOnly.length;
  if (totalParams === 0) return null;

  // Compute match percentage
  const matchPct = Math.round((pc.matches.length / totalParams) * 100);
  const pctClass = matchPct >= 80 ? "pct-good" : matchPct >= 50 ? "pct-fair" : "pct-poor";

  // Build summary label
  const parts = [];
  if (pc.matches.length > 0) parts.push(`${pc.matches.length} matched`);
  if (pc.differences.length > 0) parts.push(`${pc.differences.length} different`);
  if (pc.tiktokOnly.length > 0) parts.push(`${pc.tiktokOnly.length} TikTok-only`);
  if (pc.metaOnly.length > 0) parts.push(`${pc.metaOnly.length} Meta-only`);
  const summaryText = `<span class="param-pct ${pctClass}">${matchPct}%</span> param match — ${totalParams} parameter(s): ${parts.join(", ")}`;

  // Build param rows
  let paramRows = "";

  // Differences first (most important)
  for (const d of pc.differences) {
    paramRows += `
            <tr class="diff">
              <td><code>${esc(d.tiktokKey)}</code></td>
              <td class="val">${esc(String(d.tiktokValue))}</td>
              <td><code>${esc(d.metaKey)}</code></td>
              <td class="val">${esc(String(d.metaValue))}</td>
              <td><span class="badge count_mismatch">Different</span></td>
            </tr>`;
  }

  // TikTok-only params
  for (const p of pc.tiktokOnly) {
    paramRows += `
            <tr class="tiktok_only">
              <td><code>${esc(p.key)}</code></td>
              <td class="val">${esc(String(p.value))}</td>
              <td class="empty">—</td>
              <td class="empty">—</td>
              <td><span class="badge tiktok_only">TikTok Only</span></td>
            </tr>`;
  }

  // Meta-only params
  for (const p of pc.metaOnly) {
    paramRows += `
            <tr class="meta_only">
              <td class="empty">—</td>
              <td class="empty">—</td>
              <td><code>${esc(p.key)}</code></td>
              <td class="val">${esc(String(p.value))}</td>
              <td><span class="badge meta_only">Meta Only</span></td>
            </tr>`;
  }

  // Matched params last
  for (const m of pc.matches) {
    paramRows += `
            <tr class="match">
              <td><code>${esc(m.tiktokKey)}</code></td>
              <td class="val">${esc(String(m.value))}</td>
              <td><code>${esc(m.metaKey)}</code></td>
              <td class="val">${esc(String(m.value))}</td>
              <td><span class="badge matched">Same</span></td>
            </tr>`;
  }

  return `
          <details class="param-details">
            <summary>${summaryText}</summary>
            <table class="param-table">
              <thead>
                <tr>
                  <th>TikTok Param</th>
                  <th>TikTok Value</th>
                  <th>Meta Param</th>
                  <th>Meta Value</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>${paramRows}
              </tbody>
            </table>
          </details>`;
}

/**
 * Render a debug section showing all raw intercepted network requests
 * with their parameters in easy-to-read tables.
 */
function renderDebugSection(scanResults) {
  const pages = scanResults.map((result, i) => {
    const tiktokRows = result.tiktokRequests.map((r) => renderDebugRequest(r)).join("\n");
    const metaRows = result.metaRequests.map((r) => renderDebugRequest(r)).join("\n");
    const totalRequests = result.tiktokRequests.length + result.metaRequests.length;

    return `
      <div class="debug-page">
        <h3>Page ${i + 1}: <a href="${esc(result.url)}" target="_blank">${esc(result.url)}</a>
          <span class="debug-count">${totalRequests} request(s)</span>
        </h3>

        <h4 class="debug-platform tiktok">TikTok <span class="debug-count">${result.tiktokRequests.length}</span></h4>
        ${result.tiktokRequests.length > 0 ? tiktokRows : '<p class="no-data">No TikTok requests captured.</p>'}

        <h4 class="debug-platform meta">Meta <span class="debug-count">${result.metaRequests.length}</span></h4>
        ${result.metaRequests.length > 0 ? metaRows : '<p class="no-data">No Meta requests captured.</p>'}
      </div>`;
  }).join("\n");

  return `
  <section class="debug-section">
    <details>
      <summary><h2>Debug: Raw Network Requests</h2></summary>
      <p class="debug-intro">All intercepted pixel network calls with full parameter details.</p>
      ${pages}
    </details>
  </section>`;
}

/**
 * Render a single raw network request as a collapsible block with param tables.
 */
function renderDebugRequest(req) {
  const time = req.wallTime
    ? new Date(req.wallTime * 1000).toISOString().replace("T", " ").replace(/\.\d+Z$/, "")
    : "";

  const queryEntries = Object.entries(req.queryParams || {});
  const postEntries = Object.entries(req.postParams || {});

  const queryTable = queryEntries.length > 0
    ? renderParamTable("Query Parameters", queryEntries)
    : "";

  const postTable = postEntries.length > 0
    ? renderParamTable("POST Body", postEntries)
    : "";

  // Build a short summary label from the most identifying params
  const ev = req.queryParams?.ev || req.postParams?.ev || "";
  const label = ev ? `<code class="debug-event">${esc(ev)}</code> ` : "";

  return `
        <details class="debug-request">
          <summary>
            <span class="debug-method">${esc(req.method)}</span>
            ${label}
            <span class="debug-endpoint">${esc(req.endpoint)}</span>
            ${time ? `<span class="debug-time">${esc(time)}</span>` : ""}
          </summary>
          <div class="debug-request-body">
            <div class="debug-url"><strong>URL:</strong> <code>${esc(req.fullUrl)}</code></div>
            ${queryTable}
            ${postTable}
          </div>
        </details>`;
}

/**
 * Render a name-value parameter table for the debug section.
 */
function renderParamTable(title, entries) {
  const rows = entries.map(([key, value]) => {
    const displayValue = typeof value === "object" ? JSON.stringify(value, null, 2) : String(value);
    return `
              <tr>
                <td><code>${esc(key)}</code></td>
                <td><code class="debug-value">${esc(displayValue)}</code></td>
              </tr>`;
  }).join("\n");

  return `
            <div class="debug-param-group">
              <h5>${esc(title)} <span class="debug-count">${entries.length}</span></h5>
              <table class="debug-param-table">
                <thead><tr><th>Parameter</th><th>Value</th></tr></thead>
                <tbody>${rows}</tbody>
              </table>
            </div>`;
}

function renderObservations(observations) {
  if (!observations || observations.length === 0) return "";

  const items = observations
    .map((obs) => {
      const icon = {
        warning: "⚠",
        info: "ℹ",
        gap: "🔍",
        mismatch: "≠",
        param_diff: "≠",
        param_gap: "🔍",
        good: "✓",
        coverage: "📊",
        summary: "📋",
      }[obs.type] || "•";

      return `<li class="obs-${obs.type}"><span class="obs-icon">${icon}</span> ${esc(obs.message)}</li>`;
    })
    .join("\n");

  return `
    <div class="observations">
      <h3>Observations</h3>
      <ul>${items}</ul>
    </div>`;
}

/**
 * Escape HTML special characters to prevent XSS.
 */
function esc(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function getStyles() {
  return `
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background: #f5f7fa;
      color: #1a1a2e;
      line-height: 1.6;
      padding: 2rem;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    header {
      text-align: center;
      padding: 2rem 0;
      border-bottom: 3px solid #e0e0e0;
      margin-bottom: 2rem;
    }
    h1 { font-size: 2rem; color: #1a1a2e; }
    .subtitle { color: #666; font-size: 1.1rem; margin-top: 0.25rem; }
    .meta { color: #999; font-size: 0.85rem; margin-top: 0.5rem; }
    h2 {
      font-size: 1.4rem;
      margin: 1.5rem 0 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 2px solid #e0e0e0;
    }
    h2 a { color: #2563eb; text-decoration: none; }
    h2 a:hover { text-decoration: underline; }
    h3 { font-size: 1.1rem; margin: 1.25rem 0 0.75rem; color: #333; }
    h4 { font-size: 1rem; margin: 1rem 0 0.5rem; color: #444; }

    /* Stats */
    .stats-grid {
      display: flex;
      gap: 1rem;
      margin: 1rem 0;
      flex-wrap: wrap;
    }
    .stat-card {
      background: white;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      padding: 1.25rem;
      flex: 1;
      min-width: 150px;
      text-align: center;
      box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    .stat-card.small { padding: 1rem; }
    .stat-card.tiktok { border-left: 4px solid #00f2ea; }
    .stat-card.meta { border-left: 4px solid #1877f2; }
    .stat-value { font-size: 2rem; font-weight: 700; }
    .stat-card.tiktok .stat-value { color: #00b8b0; }
    .stat-card.meta .stat-value { color: #1877f2; }
    .stat-label { color: #666; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }
    .stat-detail { color: #999; font-size: 0.8rem; margin-top: 0.25rem; }

    /* Health card */
    .health-card {
      display: flex;
      align-items: flex-start;
      gap: 1.25rem;
      padding: 1.25rem;
      border-radius: 8px;
      border: 1px solid #e0e0e0;
      margin: 1rem 0;
    }
    .health-card.excellent { border-left: 4px solid #16a34a; background: #f0fdf4; }
    .health-card.good { border-left: 4px solid #65a30d; background: #f7fee7; }
    .health-card.fair { border-left: 4px solid #d97706; background: #fffbeb; }
    .health-card.poor { border-left: 4px solid #dc2626; background: #fef2f2; }
    .health-card.none { border-left: 4px solid #9ca3af; background: #f9fafb; }
    .health-score-ring { flex-shrink: 0; width: 64px; height: 64px; }
    .health-circle { display: block; }
    .health-circle-bg {
      fill: none; stroke: #e5e7eb; stroke-width: 3;
    }
    .health-circle-fg {
      fill: none; stroke-width: 3; stroke-linecap: round;
      transition: stroke-dasharray 0.4s;
    }
    .health-card.excellent .health-circle-fg { stroke: #16a34a; }
    .health-card.good .health-circle-fg { stroke: #65a30d; }
    .health-card.fair .health-circle-fg { stroke: #d97706; }
    .health-card.poor .health-circle-fg { stroke: #dc2626; }
    .health-card.none .health-circle-fg { stroke: #9ca3af; }
    .health-score-text {
      fill: #1a1a2e; font-size: 0.55rem; font-weight: 700;
      text-anchor: middle; dominant-baseline: middle;
    }
    .health-body { flex: 1; }
    .health-label { font-weight: 600; font-size: 1rem; margin-bottom: 0.35rem; }
    .badge.health-excellent { background: #dcfce7; color: #166534; }
    .badge.health-good { background: #ecfccb; color: #365314; }
    .badge.health-fair { background: #fef3c7; color: #92400e; }
    .badge.health-poor { background: #fee2e2; color: #991b1b; }
    .badge.health-none { background: #f3f4f6; color: #374151; }
    .health-explanation { color: #555; font-size: 0.9rem; margin-bottom: 0.5rem; }
    .health-issues {
      margin: 0; padding-left: 1.25rem;
      font-size: 0.85rem; color: #666;
      list-style: disc;
    }
    .health-issues li { padding: 0.15rem 0; }

    /* Pixel IDs */
    .pixel-ids { margin: 0.5rem 0; }
    .pixel-ids code {
      background: #f0f0f0;
      padding: 0.15rem 0.4rem;
      border-radius: 3px;
      font-size: 0.9rem;
    }

    /* Tables */
    .table-wrapper { overflow-x: auto; margin: 0.5rem 0; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,0.05);
      font-size: 0.9rem;
    }
    th {
      background: #f8f9fa;
      padding: 0.6rem 0.75rem;
      text-align: left;
      font-weight: 600;
      color: #555;
      border-bottom: 2px solid #e0e0e0;
      white-space: nowrap;
    }
    td {
      padding: 0.5rem 0.75rem;
      border-bottom: 1px solid #f0f0f0;
      vertical-align: top;
    }
    tr:last-child td { border-bottom: none; }
    tr.matched td { background: #f0fdf4; }
    tr.match td { background: #f0fdf4; }
    tr.tiktok_only td { background: #fef3c7; }
    tr.meta_only td { background: #fef3c7; }
    tr.count_mismatch td { background: #fff7ed; }
    tr.diff td { background: #fef2f2; }

    /* Badges */
    .badge {
      display: inline-block;
      padding: 0.15rem 0.5rem;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: 600;
      white-space: nowrap;
    }
    .badge.matched { background: #dcfce7; color: #166534; }
    .badge.count_mismatch { background: #ffedd5; color: #9a3412; }
    .badge.tiktok_only { background: #fef3c7; color: #92400e; }
    .badge.meta_only { background: #fef3c7; color: #92400e; }
    .badge.pageview { background: #e0e7ff; color: #3730a3; }
    .badge.ecommerce { background: #fce7f3; color: #9d174d; }
    .badge.engagement { background: #ccfbf1; color: #115e59; }
    .badge.conversion { background: #fef9c3; color: #854d0e; }
    .badge.custom { background: #f3f4f6; color: #374151; }

    /* Param sub-rows inside event table */
    tr.param-subrow > td {
      padding: 0;
      background: #fafbfc;
      border-bottom: 2px solid #e0e0e0;
    }
    .param-details {
      margin: 0;
      border: none;
    }
    .param-details summary {
      padding: 0.5rem 1rem;
      cursor: pointer;
      font-size: 0.82rem;
      color: #555;
      user-select: none;
      list-style: none;
    }
    .param-details summary::before {
      content: "\\25B6\\FE0E ";
      font-size: 0.7rem;
      display: inline-block;
      margin-right: 0.4rem;
      transition: transform 0.15s;
    }
    .param-details[open] summary::before {
      transform: rotate(90deg);
    }
    .param-details summary:hover {
      background: #f0f1f3;
    }
    .param-details .param-table {
      border-radius: 0;
      box-shadow: none;
      font-size: 0.82rem;
      margin: 0;
    }
    .param-details .param-table th {
      background: #f0f1f3;
      padding: 0.4rem 0.75rem;
      font-size: 0.78rem;
    }
    .param-details .param-table td {
      padding: 0.35rem 0.75rem;
    }
    .param-details .param-table td.val {
      max-width: 220px;
      word-break: break-all;
    }
    .param-details .param-table td.empty {
      color: #bbb;
    }
    .param-pct {
      display: inline-block;
      padding: 0.1rem 0.45rem;
      border-radius: 10px;
      font-weight: 700;
      font-size: 0.78rem;
      margin-right: 0.35rem;
    }
    .pct-good { background: #dcfce7; color: #166534; }
    .pct-fair { background: #fef3c7; color: #92400e; }
    .pct-poor { background: #fee2e2; color: #991b1b; }

    /* Params in detail section */
    code.params {
      font-size: 0.8rem;
      word-break: break-all;
      display: block;
      max-width: 400px;
    }

    /* Observations */
    .observations {
      background: white;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      padding: 1rem 1.25rem;
      margin: 1rem 0;
      box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    .observations h3 { margin-top: 0; }
    .observations ul { list-style: none; }
    .observations li {
      padding: 0.4rem 0;
      border-bottom: 1px solid #f5f5f5;
    }
    .observations li:last-child { border-bottom: none; }
    .obs-icon { margin-right: 0.5rem; }
    .obs-warning { color: #b45309; }
    .obs-gap { color: #1d4ed8; }
    .obs-mismatch { color: #c2410c; }
    .obs-param_diff { color: #dc2626; }
    .obs-param_gap { color: #7c3aed; }
    .obs-good { color: #16a34a; }
    .obs-info { color: #2563eb; }
    .obs-coverage, .obs-summary { color: #4b5563; }

    /* Details/accordions */
    details.pixel-group {
      margin: 0.5rem 0;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      overflow: hidden;
    }
    details.pixel-group summary {
      padding: 0.75rem 1rem;
      background: #f8f9fa;
      cursor: pointer;
      font-weight: 500;
    }
    details.pixel-group summary:hover { background: #f0f0f0; }
    details.pixel-group[open] summary { border-bottom: 1px solid #e0e0e0; }
    .no-data { color: #999; font-style: italic; margin: 1rem 0; }

    /* Sections */
    .summary-section, .page-section {
      background: white;
      border: 1px solid #e0e0e0;
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 2rem;
      box-shadow: 0 2px 4px rgba(0,0,0,0.04);
    }
    .page-section h2 { margin-top: 0; }

    /* Per-pixel comparison sections */
    .pixel-comparison-section {
      border: 1px solid #e8e8e8;
      border-radius: 8px;
      padding: 1rem 1.25rem;
      margin: 1rem 0;
      background: #fafbfc;
    }
    .pixel-comparison-section h3 {
      margin-top: 0;
      font-size: 1.15rem;
    }
    .pixel-comparison-section h3 code {
      background: #e0f7fa;
      padding: 0.15rem 0.5rem;
      border-radius: 4px;
      font-size: 1rem;
    }
    .pixel-comparison-meta {
      color: #666;
      font-size: 0.85rem;
      margin-bottom: 0.75rem;
    }

    /* Per-Meta-pixel sub-comparison within a TikTok pixel group */
    .meta-comparison-subsection {
      border: 1px solid #e0e0e0;
      border-radius: 6px;
      padding: 0.75rem 1rem;
      margin: 0.75rem 0;
      background: white;
    }
    .meta-comparison-subsection h4 {
      margin-top: 0;
      font-size: 1rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .meta-comparison-subsection h4 code {
      background: #e8f0fe;
      padding: 0.1rem 0.4rem;
      border-radius: 3px;
      font-size: 0.9rem;
      color: #1877f2;
    }
    .meta-event-count {
      font-weight: 400;
      font-size: 0.8rem;
      color: #888;
    }

    .redirect-notice {
      background: #eff6ff;
      border: 1px solid #bfdbfe;
      border-left: 4px solid #3b82f6;
      border-radius: 6px;
      padding: 0.75rem 1rem;
      font-size: 0.85rem;
      color: #1e40af;
      margin: 0.5rem 0 1rem;
    }
    .redirect-notice a {
      color: #1d4ed8;
      text-decoration: underline;
      word-break: break-all;
    }
    .redirect-chain {
      margin-top: 0.5rem;
    }
    .redirect-step {
      padding: 0.2rem 0;
    }
    .redirect-label {
      display: inline-block;
      min-width: 4.5rem;
      font-weight: 600;
      font-size: 0.78rem;
      color: #3b82f6;
    }
    .redirect-arrow {
      padding-left: 1.5rem;
      color: #93c5fd;
      font-size: 0.8rem;
      line-height: 1;
    }

    footer {
      text-align: center;
      padding: 2rem 0;
      color: #999;
      font-size: 0.85rem;
    }

    /* Debug section */
    .debug-section {
      background: white;
      border: 1px solid #e0e0e0;
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 2rem;
      box-shadow: 0 2px 4px rgba(0,0,0,0.04);
    }
    .debug-section > details > summary {
      cursor: pointer;
      list-style: none;
      user-select: none;
    }
    .debug-section > details > summary::before {
      content: "\\25B6\\FE0E ";
      font-size: 0.8rem;
      display: inline-block;
      margin-right: 0.5rem;
      transition: transform 0.15s;
    }
    .debug-section > details[open] > summary::before {
      transform: rotate(90deg);
    }
    .debug-section > details > summary h2 {
      display: inline;
      border-bottom: none;
      margin: 0;
      color: #666;
      font-size: 1.2rem;
    }
    .debug-intro {
      color: #888;
      font-size: 0.85rem;
      margin: 0.5rem 0 1rem;
    }
    .debug-page {
      border: 1px solid #e8e8e8;
      border-radius: 8px;
      padding: 1rem 1.25rem;
      margin: 1rem 0;
      background: #fafbfc;
    }
    .debug-page h3 {
      margin-top: 0;
      display: flex;
      align-items: center;
      gap: 0.5rem;
      flex-wrap: wrap;
    }
    .debug-platform {
      font-size: 0.95rem;
      margin: 1rem 0 0.5rem;
      padding: 0.35rem 0.75rem;
      border-radius: 4px;
      display: inline-block;
    }
    .debug-platform.tiktok { background: #e0faf9; color: #00897b; }
    .debug-platform.meta { background: #e8f0fe; color: #1565c0; }
    .debug-count {
      font-weight: 400;
      font-size: 0.8rem;
      color: #888;
      margin-left: 0.25rem;
    }
    .debug-request {
      border: 1px solid #e0e0e0;
      border-radius: 6px;
      margin: 0.5rem 0;
      background: white;
      overflow: hidden;
    }
    .debug-request summary {
      padding: 0.6rem 1rem;
      cursor: pointer;
      font-size: 0.85rem;
      display: flex;
      align-items: center;
      gap: 0.5rem;
      flex-wrap: wrap;
      list-style: none;
    }
    .debug-request summary::before {
      content: "\\25B6\\FE0E";
      font-size: 0.65rem;
      transition: transform 0.15s;
    }
    .debug-request[open] summary::before {
      transform: rotate(90deg);
    }
    .debug-request summary:hover { background: #f8f9fa; }
    .debug-method {
      background: #e8eaed;
      padding: 0.1rem 0.4rem;
      border-radius: 3px;
      font-weight: 600;
      font-size: 0.75rem;
      font-family: monospace;
    }
    .debug-event {
      background: #fff3e0;
      padding: 0.1rem 0.4rem;
      border-radius: 3px;
      font-size: 0.82rem;
      color: #e65100;
    }
    .debug-endpoint {
      color: #666;
      font-size: 0.8rem;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: 400px;
    }
    .debug-time {
      color: #aaa;
      font-size: 0.75rem;
      margin-left: auto;
    }
    .debug-request-body {
      padding: 0.75rem 1rem;
      border-top: 1px solid #f0f0f0;
      background: #fafbfc;
    }
    .debug-url {
      font-size: 0.8rem;
      margin-bottom: 0.75rem;
      word-break: break-all;
    }
    .debug-url code {
      font-size: 0.78rem;
      color: #555;
    }
    .debug-param-group {
      margin: 0.5rem 0;
    }
    .debug-param-group h5 {
      font-size: 0.82rem;
      color: #555;
      margin: 0.5rem 0 0.25rem;
    }
    .debug-param-table {
      font-size: 0.82rem;
    }
    .debug-param-table th {
      background: #f0f1f3;
      padding: 0.35rem 0.75rem;
      font-size: 0.78rem;
    }
    .debug-param-table td {
      padding: 0.3rem 0.75rem;
    }
    .debug-param-table td:first-child {
      white-space: nowrap;
      font-weight: 500;
      width: 180px;
      min-width: 120px;
    }
    .debug-value {
      word-break: break-all;
      font-size: 0.78rem;
      white-space: pre-wrap;
      color: #333;
    }

    @media (max-width: 768px) {
      body { padding: 1rem; }
      .stats-grid { flex-direction: column; }
    }
  `;
}

module.exports = { generateReport };
